### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/clojurescript#34]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/clojurescript/issues/25)
- [ ] [Add key features](https://github.com/exercism/clojurescript/issues/26)
- [ ] [Add tags](https://github.com/exercism/clojurescript/issues/27)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/clojurescript/issues/28)
- [ ] [Update status of track](https://github.com/exercism/clojurescript/issues/32)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/clojurescript/issues/33)
- [ ] [Pass linting checks](https://github.com/exercism/clojurescript/issues/29)
- [ ] [Build Test Runner](https://github.com/exercism/clojurescript/issues/30)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/clojurescript/issues/31) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
